### ISSUE TITLE
Forms menu not present -- no way to paste into a box from menu

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/otter-browser-os2#9]
In the windows version a menu is present for a box like this one taht provides simple editting tools (copy, cut, paste, delete etc including spell check and dictionary selection). This menu is not present in the OS2 version only shows the standard browser menu (back, forward,etc). Additionally paste is greyed out on the edit menu leaving keyboard accel key as the only way to paste.

**Comment by dmik** [comment]
This seems to be fixed in Otter weekly update 409. I imported code from weekly update 424 (see bb317bbbfc1b173d8ede53e0f30e1366f3f5202a) and both the context menu and the Edit menu now work as they should. Closing this. Please check as soon as you get a new test build (later).

PS. From https://otter-browser.org:

> Weekly report #409 (2021-11-01)
QWE context menu is now usable again:
8 commits by one author,
no new issues,
218 issues still open (including 7 bugs).
